import type { ItemName } from 'mindustry-schematic-parser';

export const items: ItemName[] = [
  'beryllium',
  'blast-compound',
  'carbide',
  'coal',
  'copper',
  'dormant-cyst',
  'fissile-matter',
  'graphite',
  'lead',
  'metaglass',
  'metaglass',
  'oxide',
  'phase-fabric',
  'plastanium',
  'pyratite',
  'sand',
  'scrap',
  'spore-pod',
  'surge-alloy',
  'thorium',
  'titanium',
  'tungsten',
];
